package com.adyen.testcards.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

private val primaryLight = Color(0xFF00BE5A)
private val onPrimaryLight = Color(0xFFFFFFFF)
private val primaryContainerLight = Color(0xFF25CA65)
private val onPrimaryContainerLight = Color(0xFF002D10)
private val secondaryLight = Color(0xFF003EBE)
private val onSecondaryLight = Color(0xFFFFFFFF)
private val secondaryContainerLight = Color(0xFF2C62FA)
private val onSecondaryContainerLight = Color(0xFFFFFFFF)
private val tertiaryLight = Color(0xFF000000)
private val onTertiaryLight = Color(0xFFFFFFFF)
private val tertiaryContainerLight = Color(0xFF182541)
private val onTertiaryContainerLight = Color(0xFFA4B1D3)
private val errorLight = Color(0xFFA50011)
private val onErrorLight = Color(0xFFFFFFFF)
private val errorContainerLight = Color(0xFFDF2B2B)
private val onErrorContainerLight = Color(0xFFFFFFFF)
private val backgroundLight = Color(0xFFF3FCEF)
private val onBackgroundLight = Color(0xFF161D16)
private val surfaceLight = Color(0xFFFCF8F8)
private val onSurfaceLight = Color(0xFF1C1B1B)
private val surfaceVariantLight = Color(0xFFE0E3E3)
private val onSurfaceVariantLight = Color(0xFF444748)
private val outlineLight = Color(0xFF747878)
private val outlineVariantLight = Color(0xFFC4C7C8)
private val scrimLight = Color(0xFF000000)
private val inverseSurfaceLight = Color(0xFF313030)
private val inverseOnSurfaceLight = Color(0xFFF4F0EF)
private val inversePrimaryLight = Color(0xFF46E178)
private val surfaceDimLight = Color(0xFFDDD9D9)
private val surfaceBrightLight = Color(0xFFFCF8F8)
private val surfaceContainerLowestLight = Color(0xFFFFFFFF)
private val surfaceContainerLowLight = Color(0xFFF6F3F2)
private val surfaceContainerLight = Color(0xFFF1EDEC)
private val surfaceContainerHighLight = Color(0xFFEBE7E7)
private val surfaceContainerHighestLight = Color(0xFFE5E2E1)

private val primaryDark = Color(0xFF00BE5A)
private val onPrimaryDark = Color(0xFF003916)
private val primaryContainerDark = Color(0xFF00B555)
private val onPrimaryContainerDark = Color(0xFF001204)
private val secondaryDark = Color(0xFFB6C4FF)
private val onSecondaryDark = Color(0xFF00277F)
private val secondaryContainerDark = Color(0xFF1B57F0)
private val onSecondaryContainerDark = Color(0xFFFFFFFF)
private val tertiaryDark = Color(0xFFB9C6EA)
private val onTertiaryDark = Color(0xFF23304C)
private val tertiaryContainerDark = Color(0xFF000A22)
private val onTertiaryContainerDark = Color(0xFF8E9BBC)
private val errorDark = Color(0xFFFFB4AC)
private val onErrorDark = Color(0xFF690007)
private val errorContainerDark = Color(0xFFD62326)
private val onErrorContainerDark = Color(0xFFFFFFFF)
private val backgroundDark = Color(0xFF0E150E)
private val onBackgroundDark = Color(0xFFDCE5D9)
private val surfaceDark = Color(0xFF141313)
private val onSurfaceDark = Color(0xFFE5E2E1)
private val surfaceVariantDark = Color(0xFF444748)
private val onSurfaceVariantDark = Color(0xFFC4C7C8)
private val outlineDark = Color(0xFF8E9192)
private val outlineVariantDark = Color(0xFF444748)
private val scrimDark = Color(0xFF000000)
private val inverseSurfaceDark = Color(0xFFE5E2E1)
private val inverseOnSurfaceDark = Color(0xFF313030)
private val inversePrimaryDark = Color(0xFF006D31)
private val surfaceDimDark = Color(0xFF141313)
private val surfaceBrightDark = Color(0xFF3A3939)
private val surfaceContainerLowestDark = Color(0xFF0E0E0E)
private val surfaceContainerLowDark = Color(0xFF1C1B1B)
private val surfaceContainerDark = Color(0xFF201F1F)
private val surfaceContainerHighDark = Color(0xFF2A2A2A)
private val surfaceContainerHighestDark = Color(0xFF353434)

internal val lightScheme = lightColorScheme(
    primary = primaryLight,
    onPrimary = onPrimaryLight,
    primaryContainer = primaryContainerLight,
    onPrimaryContainer = onPrimaryContainerLight,
    secondary = secondaryLight,
    onSecondary = onSecondaryLight,
    secondaryContainer = secondaryContainerLight,
    onSecondaryContainer = onSecondaryContainerLight,
    tertiary = tertiaryLight,
    onTertiary = onTertiaryLight,
    tertiaryContainer = tertiaryContainerLight,
    onTertiaryContainer = onTertiaryContainerLight,
    error = errorLight,
    onError = onErrorLight,
    errorContainer = errorContainerLight,
    onErrorContainer = onErrorContainerLight,
    background = backgroundLight,
    onBackground = onBackgroundLight,
    surface = surfaceLight,
    onSurface = onSurfaceLight,
    surfaceVariant = surfaceVariantLight,
    onSurfaceVariant = onSurfaceVariantLight,
    outline = outlineLight,
    outlineVariant = outlineVariantLight,
    scrim = scrimLight,
    inverseSurface = inverseSurfaceLight,
    inverseOnSurface = inverseOnSurfaceLight,
    inversePrimary = inversePrimaryLight,
    surfaceDim = surfaceDimLight,
    surfaceBright = surfaceBrightLight,
    surfaceContainerLowest = surfaceContainerLowestLight,
    surfaceContainerLow = surfaceContainerLowLight,
    surfaceContainer = surfaceContainerLight,
    surfaceContainerHigh = surfaceContainerHighLight,
    surfaceContainerHighest = surfaceContainerHighestLight,
)

internal val darkScheme = darkColorScheme(
    primary = primaryDark,
    onPrimary = onPrimaryDark,
    primaryContainer = primaryContainerDark,
    onPrimaryContainer = onPrimaryContainerDark,
    secondary = secondaryDark,
    onSecondary = onSecondaryDark,
    secondaryContainer = secondaryContainerDark,
    onSecondaryContainer = onSecondaryContainerDark,
    tertiary = tertiaryDark,
    onTertiary = onTertiaryDark,
    tertiaryContainer = tertiaryContainerDark,
    onTertiaryContainer = onTertiaryContainerDark,
    error = errorDark,
    onError = onErrorDark,
    errorContainer = errorContainerDark,
    onErrorContainer = onErrorContainerDark,
    background = backgroundDark,
    onBackground = onBackgroundDark,
    surface = surfaceDark,
    onSurface = onSurfaceDark,
    surfaceVariant = surfaceVariantDark,
    onSurfaceVariant = onSurfaceVariantDark,
    outline = outlineDark,
    outlineVariant = outlineVariantDark,
    scrim = scrimDark,
    inverseSurface = inverseSurfaceDark,
    inverseOnSurface = inverseOnSurfaceDark,
    inversePrimary = inversePrimaryDark,
    surfaceDim = surfaceDimDark,
    surfaceBright = surfaceBrightDark,
    surfaceContainerLowest = surfaceContainerLowestDark,
    surfaceContainerLow = surfaceContainerLowDark,
    surfaceContainer = surfaceContainerDark,
    surfaceContainerHigh = surfaceContainerHighDark,
    surfaceContainerHighest = surfaceContainerHighestDark,
)
