name: Check Labels

# Every PR should have a label and some labels should include an update to the release notes
on:
  pull_request:
    types: [ labeled, unlabeled, edited ]
  issues:
    types:
      - labeled

jobs:
  check_labels:
    runs-on: ubuntu-latest

    steps:
      - name: Check Labels
        run: |
          echo -e "Running check labels"
