name: Create release notes PR

on:
  workflow_call:
    inputs:
      version-name:
        required: true
        type: string
      encoded-release-notes:
        required: true
        type: string

jobs:
  create_release_notes_pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create release notes PR
        env:
          VERSION_NAME: ${{ inputs.version-name }}
          ENCODED_RELEASE_NOTES: ${{ inputs.encoded-release-notes }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: ${{ github.repository }}
        run: |
          BASE_BRANCH="release-notes"
          RELEASE_NOTES_FILE="$VERSION_NAME.md"
          RELEASE_NOTES=$(echo "$ENCODED_RELEASE_NOTES" | base64 --decode)

          # Ensure git is set up properly
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

          # Check out the base branch
          git fetch origin "$BASE_BRANCH"
          git checkout "$BASE_BRANCH"

          # Create and switch to the new branch
          git checkout -b "$VERSION_NAME"

          # Write the release notes to the file
          echo "$RELEASE_NOTES" > "$RELEASE_NOTES_FILE"

          # Add, commit, and push the changes
          git add "$RELEASE_NOTES_FILE"
          git commit -m "Add release notes for $VERSION_NAME release"
          git push origin "$VERSION_NAME"

          # Create a pull request using the GitHub API
          API_URL="https://api.github.com/repos/$GITHUB_REPO/pulls"
          PR_TITLE="Create release notes for $VERSION_NAME release"
          PR_BODY="This PR adds release notes for the $VERSION_NAME release."
          JSON_PAYLOAD=$(cat <<EOF
          {
            "title": "$PR_TITLE",
            "head": "$NEW_BRANCH",
            "base": "$BASE_BRANCH",
            "body": "$PR_BODY"
          }
          EOF
          )

          curl -s -X POST -H "Authorization: token $GITHUB_TOKEN" \
          -H "Content-Type: application/json" \
          -d "$JSON_PAYLOAD" "$API_URL"
