name: Finalize release

on:
  workflow_dispatch:
    inputs:
      version-name:
        description: "Version name of the build"
        required: true
        type: string

jobs:
  update_release_notes:
    name: Update release notes
    uses: ./.github/workflows/update_release_notes.yml
    secrets: inherit
    needs: fetch_version_name
    with:
      version-name: ${{ inputs.version-name }}
  publish_github_release:
    name: Update release notes
    uses: ./.github/workflows/publish_github_release.yml
    secrets: inherit
    needs: [fetch_version_name, update_release_notes]
    with:
      version-name: ${{ inputs.version-name }}
