name: Manage stale contributions

on:
  schedule:
    - cron: '0 0 * * *'  # Run every day at midnight

jobs:
  manage_stale_contributions:
    runs-on: ubuntu-latest
    steps:
      - name: Manage stale contributions
        uses: actions/stale@v9
        with:
          any-of-issue-labels: 'Needs more info'
          stale-issue-message: 'This issue is now stale because it has been open for 14 days with no activity. Please provide the requested information or the issue will be closed automatically.'
          close-issue-message: 'This issue is now closed because it has been stale for 14 days with no activity.'
          days-before-issue-stale: 14
          days-before-issue-close: 14
          stale-pr-message: 'This PR is now stale because it has been open for 30 days with no activity. Please provide the requested information or the issue will be closed automatically.'
          close-pr-message: 'This issue is now closed because it has been stale for 14 days with no activity.'
          days-before-pr-stale: 30
          days-before-pr-close: 7
